version: "2"
services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: $CONTAINER_NAME
    restart: unless-stopped
    environment:
      - PORTAINER_DOMAIN=$PORTAINER_DOMAIN
      - CONTAINER_NAME=$CONTAINER_NAME
      - DATA_FOLDER=$DATA_FOLDER
    security_opt:
      - no-new-privileges:true
    ports:
      - 11443:9443
    command: --sslcert /certs/fullchain.pem
      --sslkey /certs/privkey.pem
    entrypoint:
      - "/portainer"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - $DATA_FOLDER:/data
      - /srv/docker/swag/etc/letsencrypt/live/$PORTAINER_DOMAIN/fullchain.pem:/certs/fullchain.pem:ro
      - /srv/docker/swag/etc/letsencrypt/live/$PORTAINER_DOMAIN/privkey.pem:/certs/privkey.pem:ro
