---
version: "2"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: $CONTAINER_NAME
    cap_add:
      - NET_ADMIN
    environment:
      - DATA_FOLDER=$DATA_FOLDER
      - SWAG_DOMAIN=$SWAG_DOMAIN
      - SWAG_SUBDOMAINS=$SWAG_SUBDOMAINS
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - URL=$SWAG_DOMAIN
      - SUBDOMAINS=$SWAG_SUBDOMAINS
      - VALIDATION=http
      - CERTPROVIDER= #optional
      - DNSPLUGIN=cloudflare #optional
      - PROPAGATION= #optional
      - EMAIL= #optional
      - ONLY_SUBDOMAINS=false #optional
      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - $DATA_FOLDER:/config
    ports:
      - 443:443
      - 80:80 
    restart: unless-stopped
