version: "2"
services:
  nextcloud:
    build: .
    container_name: $CONTAINER_NAME
    restart: always
    hostname: "nextcloud.$NEXTCLOUD_DOMAIN"
    ports:
      - "11443:443"
    environment:
      - CONTAINER_NAME=$CONTAINER_NAME
      - DATA_FOLDER=$DATA_FOLDER
      - NEXTCLOUD_DOMAIN=$NEXTCLOUD_DOMAIN
    volumes:
      - "$DATA_FOLDER/nextcloud:/var/www/html"
      - "$DATA_FOLDER/apps:/var/www/html/custom_apps"
      - "$DATA_FOLDER/config:/var/www/html/config"
      - "$DATA_FOLDER/data:/var/www/html/data"
      - "$DATA_FOLDER/../apache2.conf:/etc/apache2/sites-enabled/default-ssl.conf"
      - "$DATA_FOLDER/../apache2.conf:/etc/apache2/sites-available/default-ssl.conf"
      - "/srv/docker/swag/etc/letsencrypt/live/$NEXTCLOUD_DOMAIN/fullchain.pem:/certs/fullchain.pem:ro"
      - "/srv/docker/swag/etc/letsencrypt/live/$NEXTCLOUD_DOMAIN/privkey.pem:/certs/privkey.pem:ro"
    shm_size: "256m"
