version: '2'
services:
  nextcloud:
    build: .
    container_name: nextcloud
      #restart: always
    hostname: 'nextcloud.$NEXTCLOUD_DOMAIN'
    ports:
      - '11443:443'
    environment:
      - DATA_FOLDER=$DATA_FOLDER
      - NEXTCLOUD_DOMAIN=$NEXTCLOUD_DOMAIN
    volumes:
      - '$DATA_FOLDER/nextcloud:/var/www/html'
      - '$DATA_FOLDER/apps:/var/www/html/custom_apps'
      - '$DATA_FOLDER/config:/var/www/html/config'
      - '$DATA_FOLDER/data:/var/www/html/data'
      - '$DATA_FOLDER/../apache2.conf:/etc/apache2/sites-enabled/default-ssl.conf'
      - '$DATA_FOLDER/../apache2.conf:/etc/apache2/sites-available/default-ssl.conf'
      - '/etc/letsencrypt/etc/letsencrypt/archive/$NEXTCLOUD_DOMAIN:/certs:ro'
    shm_size: '256m'
