version: "2"
services:
  nextcloud:
    image: nextcloud
    # build: .
    container_name: $CONTAINER_NAME
    restart: always
    hostname: "nextcloud.$NEXTCLOUD_DOMAIN"
    ports:
      - "127.0.0.1:12080:80"
    environment:
      - CONTAINER_NAME=$CONTAINER_NAME
      - DATA_FOLDER=$DATA_FOLDER
      - NEXTCLOUD_DOMAIN=$NEXTCLOUD_DOMAIN
    volumes:
      - "$DATA_FOLDER/nextcloud:/var/www/html"
      - "$DATA_FOLDER/apps:/var/www/html/custom_apps"
      - "$DATA_FOLDER/config:/var/www/html/config"
      - "$DATA_FOLDER/data:/var/www/html/data"
    shm_size: "256m"
